# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.AddField(
            model_name='article',
            name='disqus_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
