# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20160121_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentauthor',
            name='disqus_id',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='commentauthor',
            name='joined_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='commentauthor',
            name='username',
            field=models.TextField(null=True),
        ),
    ]
