# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-12 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20160121_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='json_flatten',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
