# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-13 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='from_str',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='to_str',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
