# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-13 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20160213_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='explanation',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
