# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-14 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20160213_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='summary',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
