# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_comment_is_replacement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.CommentAuthor'),
        ),
    ]
