# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-13 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20160218_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='num_replies',
            field=models.IntegerField(default=0),
        ),
    ]
