# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-13 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_comment_num_replies'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text_len',
            field=models.IntegerField(default=0),
        ),
    ]
