# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-15 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_comment_text_len'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='num_subchildren',
            field=models.IntegerField(default=0),
        ),
    ]
