# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-18 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_auto_20160318_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='vector',
            field=models.BinaryField(),
        ),
    ]
