# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-30 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_auto_20160318_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='extra_summary',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
