# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-25 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_auto_20160423_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(),
        ),
    ]
