# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-26 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_auto_20160425_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reply_to',
        ),
        migrations.AlterField(
            model_name='comment',
            name='disqus_id',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='comment',
            name='reply_to_disqus',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
