# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-26 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_auto_20160426_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='disqus_id',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='comment',
            name='reply_to_disqus',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
