# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-27 07:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_auto_20160426_0440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('color', models.CharField(max_length=6)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Article')),
            ],
        ),
        migrations.CreateModel(
            name='TagComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Comment')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Tag')),
            ],
        ),
    ]
