# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-27 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_auto_20160427_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
