# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-27 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_article_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='highlight_authors',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
