# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-11 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_article_highlight_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='cosigners',
            field=models.ManyToManyField(related_name='cosigned_on', to='website.CommentAuthor'),
        ),
        migrations.AddField(
            model_name='commentauthor',
            name='edit_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commentauthor',
            name='gender',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='commentauthor',
            name='groups',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='commentauthor',
            name='is_wikipedia',
            field=models.BooleanField(default=False),
        ),
    ]
