# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-07 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_auto_20161111_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='access_mode',
            field=models.IntegerField(choices=[(1, 'Edit'), (2, 'Comment'), (3, 'View'), (4, 'Private')], default=1),
        ),
    ]
