# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-04 11:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_comment_collapsed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='collapsed',
        ),
    ]
