# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-09 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0034_article_access_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='percent_complete',
            field=models.IntegerField(default=0),
        ),
    ]
