# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-09 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_article_percent_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='comment_num',
            field=models.IntegerField(default=0),
        ),
    ]
