# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-06-28 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0037_article_summary_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='section_index',
            field=models.IntegerField(default=0),
        ),
    ]
