# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-11-08 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0039_change_comment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentauthor',
            name='is_decide',
            field=models.BooleanField(default=False),
        ),
    ]
