# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-10-17 05:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0039_change_comment_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Article')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='summary_dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='summary_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metacomment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Comment'),
        ),
        migrations.AddField(
            model_name='metacomment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
