# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-11-08 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0040_article_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='suggested_tags',
            field=models.ManyToManyField(related_name='suggested_comments', to='website.Tag'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='tags',
            field=models.ManyToManyField(related_name='comments', to='website.Tag'),
        ),
    ]
