# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-11-08 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0041_auto_20171108_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentauthor',
            name='is_decide',
            field=models.BooleanField(default=False),
        ),
    ]
