# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-11-10 21:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0042_commentauthor_is_decide'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentRating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('neutral_rating', models.IntegerField(null=True)),
                ('coverage_rating', models.IntegerField(null=True)),
                ('quality_rating', models.IntegerField(null=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
