# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-05-27 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0043_commentrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='disqus_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
