# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-05-27 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0045_commentauthor_is_join'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentauthor',
            name='disqus_id',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
