# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-08-25 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0048_auto_20180824_0427'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='last_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
