# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-08-26 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0049_article_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='action',
            field=models.CharField(max_length=20),
        ),
    ]
