# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-09-02 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0051_auto_20180827_0354'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='import_order',
            field=models.IntegerField(default=0),
        ),
    ]
