# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-03-06 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0052_comment_import_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='summarized',
            field=models.BooleanField(default=False),
        ),
    ]
