# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-04-18 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0053_comment_summarized'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentauthor',
            name='is_wikum',
            field=models.BooleanField(default=False),
        ),
    ]
