# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-04-21 04:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0054_commentauthor_is_wikum'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentauthor',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
