# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-04-21 05:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0055_commentauthor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentauthor',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
