# Generated by Django 2.1.1 on 2020-01-10 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0058_comment_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='words_shown',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='history',
            name='current_percent_complete',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='history',
            name='words_shown',
            field=models.IntegerField(default=0),
        ),
    ]
