# Generated by Django 2.1.1 on 2020-02-18 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0059_auto_20200110_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='sibling_prev',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
