# Generated by Django 2.1.1 on 2020-02-18 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0060_comment_sibling_prev'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='last_child',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
