# Generated by Django 2.1.1 on 2020-02-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0061_comment_last_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='last_child',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
