# Generated by Django 2.1.1 on 2020-02-20 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0062_article_last_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='first_child',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='first_child',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='sibling_next',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
