# Generated by Django 2.1.1 on 2020-02-20 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0063_auto_20200220_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='first_child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_first_child', to='website.Comment'),
        ),
        migrations.AlterField(
            model_name='article',
            name='last_child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_last_child', to='website.Comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='first_child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_first_child', to='website.Comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='last_child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_last_child', to='website.Comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='sibling_next',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_next_sib', to='website.Comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='sibling_prev',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_prev_sib', to='website.Comment'),
        ),
    ]
