# Generated by Django 2.1.1 on 2020-02-26 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0065_auto_20200226_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='first_child',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='last_child',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='first_child',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='last_child',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='sibling_next',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='sibling_prev',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
