# Generated by Django 2.1.1 on 2020-03-02 15:58

from django.db import migrations

# Reset all links in the articles by ID value
def set_links_all_articles(apps, schema_editor):
    '''
    We can't import the Post model directly as it may be a newer
    version than this migration expects. We use the historical version.
    '''
    Article = apps.get_model('website', 'Article')
    for article in Article.objects.all():
        set_link_article(apps, article, article)

def set_link_article(apps, node, article):
    if node == article:
        disqus_id = None
    else:
        disqus_id = node.disqus_id
    Comment = apps.get_model('website', 'Comment')
    children = Comment.objects.filter(reply_to_disqus=disqus_id, article=article).order_by('import_order')
    if len(children) == 0:
        node.first_child = None
        node.last_child = None
        node.save()
    else:
        node.first_child = children[0].disqus_id
        node.last_child = children[len(children)-1].disqus_id
        node.save()
        if len(children) == 1:
            children[0].sibling_prev = None
            children[0].sibling_next = None
            children[0].save()
            set_link_article(apps, children[0], article)
        else:
            for index, child in enumerate(children):
                if index == 0:
                    child.sibling_prev = None
                    child.sibling_next = children[index + 1].disqus_id
                elif index == len(children)-1:
                    child.sibling_next = None
                    child.sibling_prev = children[index - 1].disqus_id
                else:
                    child.sibling_prev = children[index - 1].disqus_id
                    child.sibling_next = children[index + 1].disqus_id
                child.save()
                set_link_article(apps, child, article)

class Migration(migrations.Migration):

    dependencies = [
        ('website', '0066_auto_20200226_0153'),
    ]

    operations = [
    	migrations.RunPython(set_links_all_articles),
    ]
