# Generated by Django 3.0.5 on 2020-04-03 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0069_wikumuser'),
        ('website', '0068_article_drag_locked'),
    ]

    operations = [
    ]
