# Generated by Django 3.0.5 on 2020-04-14 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0073_auto_20200413_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='content',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
